### ISSUE TITLE
Diarization is broken

### ISSUE THREAD

**Issue by rroohhh** [transcribee/transcribee#109]
```
worker   | WARNING:root:Worker failed with exception
worker   | Traceback (most recent call last):
worker   |   File "/data/projects/transcribee/transcribee/worker/transcribee_worker/worker.py", line 315, in run_task
worker   |     task_result = await self.perform_task(task)
worker   |   File "/data/projects/transcribee/transcribee/worker/transcribee_worker/worker.py", line 110, in perform_task
worker   |     await self.diarize(task)
worker   |   File "/data/projects/transcribee/transcribee/worker/transcribee_worker/worker.py", line 213, in diarize
worker   |     diarization = diarize(document_audio, progress_callback=progress_callback)
worker   |   File "/data/projects/transcribee/transcribee/worker/transcribee_worker/diarize.py", line 65, in diarize
worker   |     diarization = pipeline(audio, hook=_hook)
worker   |   File "/data/projects/transcribee/transcribee/worker/__pypackages__/3.10/lib/pyannote/audio/core/pipeline.py", line 324, in __call__
worker   |     return self.apply(file, **kwargs)
worker   |   File "/data/projects/transcribee/transcribee/worker/__pypackages__/3.10/lib/pyannote/audio/pipelines/speaker_diarization.py", line 496, in apply
worker   |     embeddings = self.get_embeddings(
worker   |   File "/data/projects/transcribee/transcribee/worker/__pypackages__/3.10/lib/pyannote/audio/pipelines/speaker_diarization.py", line 337, in get_embeddings
worker   |     embedding_batch: np.ndarray = self._embedding(
worker   |   File "/data/projects/transcribee/transcribee/worker/__pypackages__/3.10/lib/pyannote/audio/pipelines/speaker_verification.py", line 318, in __call__
worker   |     assert num_channels == 1
worker   | AssertionError
```

**Comment by pajowu** [comment]
Might be fixed once we reencode the audio (#59)
